---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-user
  namespace: default

---
kind: Role 
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins-user-configmap-access
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["production-eu-prometheus-server"]
  verbs: ["update", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins-user
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins-user
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-user-configmap-access 
